name: Go

on:
  push:
    branches: [ main feature/**, bugfix/**, ops/** ]
  pull_request:
    types: [ closed ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v2
