name: Barton CI/CD pipeline

on:
  push:
    branches: [ main feature/**, bugfix/**, ops/** ]
  pull_request:
    types: [ closed ]
  workflow_dispatch:
    inputs:
      purpose:
        description: 'Purpose of manual run'
        required: true
        default: 'Manual verification'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v2
